#!/bin/sh

set -e

LEEWISE_LIB_DIR=/var/lib/leewise
LEEWISE_USER="leewise"
LEEWISE_GROUP="leewise"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $LEEWISE_USER || true
        delgroup --quiet --system --only-if-empty $LEEWISE_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-leewise-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$LEEWISE_LIB_DIR" ]; then
            rm -rf $LEEWISE_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
