#!/bin/sh

set -e

LEEWISE_CONFIGURATION_FILE=/etc/leewise/leewise.conf
LEEWISE_GROUP="leewise"
LEEWISE_DATA_DIR=/var/lib/leewise
LEEWISE_LOG_DIR=/var/log/leewise
LEEWISE_USER="leewise"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^leewise:"; then
            adduser --system --home $LEEWISE_DATA_DIR --quiet --group $LEEWISE_USER
            # Data dir
            chown $LEEWISE_USER:$LEEWISE_GROUP $LEEWISE_DATA_DIR
        fi
        # Register "$LEEWISE_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $LEEWISE_USER" 2> /dev/null || true
        # Configuration file
        chown $LEEWISE_USER:$LEEWISE_GROUP $LEEWISE_CONFIGURATION_FILE
        chmod 0640 $LEEWISE_CONFIGURATION_FILE
        # Log
        mkdir -p $LEEWISE_LOG_DIR
        chown $LEEWISE_USER:$LEEWISE_GROUP $LEEWISE_LOG_DIR
        chmod 0750 $LEEWISE_LOG_DIR
        	# work around https://bugs.debian.org/1059326

        if ! [ -e ${GSFONTS_DIR}/n021003l.pfb ] ; then
            if ! [ -d ${GSFONTS_DIR} ] ; then
                mkdir ${GSFONTS_DIR}
                touch ${GSFONTS_DIR}/.created-by-leewise-package
            fi
            ln -s /usr/share/fonts/X11/Type1/C059-Roman.pfb ${GSFONTS_DIR}/n021003l.pfb
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
